# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba62d1a081185cff352e5fdea706a0a7a9907d7da8e9b43810a5f88da7dfb321988dcaaaab3bc53e2f96a481596eb5016bffb07f42a473e340bc973c011cdbc2

test:
  secret_key_base: 0d728f82efd1120d2dbcb0ede4e41472b493048a074bec7ed551c28b88f26d242178f367ffdcbfe6f7b7508b7b2a925aefbf75bbea036934f6756bddbd9f4462

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
